import type { Metadata } from "next";
import { Google_Sans, Urbanist } from "next/font/google";
import "./globals.css";

const sans = Google_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
});

const serif = Urbanist({
  variable: "--font-serif",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${sans.variable} ${serif.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans">{children}</body>
    </html>
  );
}
