CREATE TABLE trips (
    id SERIAL PRIMARY KEY,
    trip_number VARCHAR(20) UNIQUE NOT NULL,
    vehicle_id INTEGER NOT NULL REFERENCES vehicles(id) ON UPDATE NO ACTION,
    driver_id INTEGER NOT NULL REFERENCES drivers(id) ON UPDATE NO ACTION,
    route_id INTEGER REFERENCES routes(id) ON UPDATE NO ACTION,
    created_by INTEGER NOT NULL REFERENCES users(id) ON UPDATE NO ACTION,
    source VARCHAR(100) NOT NULL,
    destination VARCHAR(100) NOT NULL,
    cargo_type VARCHAR(100),
    cargo_weight DECIMAL(10, 2) NOT NULL,
    planned_distance DECIMAL(10, 2) NOT NULL,
    actual_distance DECIMAL(10, 2),
    planned_start TIMESTAMP(6) NOT NULL,
    actual_start TIMESTAMP(6),
    actual_end TIMESTAMP(6),
    fuel_consumed DECIMAL(10, 2),
    start_odometer INTEGER NOT NULL,
    end_odometer INTEGER,
    revenue DECIMAL(12, 2),
    status VARCHAR(20) NOT NULL,
    remarks TEXT,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
);
